#pragma once

#define FUNCONF_USE_HSI 1
#define FUNCONF_USE_HSE 0
#define FUNCONF_SYSTEM_CORE_CLOCK 48000000
#define FUNCONF_USE_5V_VDD 0
#define FUNCONF_USE_DEBUGPRINTF 0
#define FUNCONF_USE_UARTPRINTF 0
#define FUNCONF_USE_USBPRINTF 0
#define FUNCONF_NULL_PRINTF 1
#define FUNCONF_DEBUG_HARDFAULT 0
